<x-guest-layout>
    <div class="auth-heading"><p class="auth-eyebrow">Create your SPS account</p><h1>Register account</h1><p>Start organising your student life today.</p></div>
    <form method="POST" action="{{ route('register') }}" class="auth-form" data-loading>@csrf
        <div class="auth-grid"><div><label for="name">Full Name</label><input id="name" type="text" name="name" value="{{ old('name') }}" required autofocus autocomplete="name" placeholder="Full name">@error('name')<p class="auth-error">{{ $message }}</p>@enderror</div><div><label for="student_id">Student ID / Number</label><input id="student_id" type="text" name="student_id" value="{{ old('student_id') }}" required autocomplete="student_id" placeholder="Student ID">@error('student_id')<p class="auth-error">{{ $message }}</p>@enderror</div></div>
        <div><label for="email">Email</label><input id="email" type="email" name="email" value="{{ old('email') }}" required autocomplete="username" placeholder="you@example.com">@error('email')<p class="auth-error">{{ $message }}</p>@enderror</div>
        <div class="auth-grid"><div><label for="course">Program</label><input id="course" type="text" name="course" value="{{ old('course') }}" required autocomplete="course" placeholder="Your program">@error('course')<p class="auth-error">{{ $message }}</p>@enderror</div><div><label for="semester">Semester</label><select id="semester" name="semester" required><option value="">Select semester</option>@for($semester = 1; $semester <= 4; $semester++)<option value="{{ $semester }}" @selected(old('semester') == $semester)>Semester {{ $semester }}</option>@endfor</select>@error('semester')<p class="auth-error">{{ $message }}</p>@enderror</div></div>
        <div class="auth-grid"><div><label for="password">Password</label><div class="auth-password"><input id="password" type="password" name="password" required autocomplete="new-password" placeholder="Create password"><button type="button" data-password-toggle="#password" aria-label="Show password">Show</button></div>@error('password')<p class="auth-error">{{ $message }}</p>@enderror</div><div><label for="password_confirmation">Confirm Password</label><div class="auth-password"><input id="password_confirmation" type="password" name="password_confirmation" required autocomplete="new-password" placeholder="Confirm password"><button type="button" data-password-toggle="#password_confirmation" aria-label="Show password">Show</button></div></div></div>
        <button type="submit" class="auth-submit">Register</button><p class="auth-links auth-links-centered">Already have an account? <a href="{{ route('login') }}">Log in here</a></p>
    </form>
</x-guest-layout>
